// <auto-generated />
using System;
using DomusMind.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomusMind.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DomusMindDbContext))]
    partial class DomusMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomusMind.Domain.Calendar.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("_participantIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("participant_ids");

                    b.Property<string>("_reminderOffsets")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reminder_offsets");

                    b.HasKey("Id");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at_utc");

                    b.Property<string>("AccountDisplayLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_display_label");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("account_email");

                    b.Property<string>("CachedAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("cached_access_token");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("GrantedScopes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("granted_scopes");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastSuccessfulSyncUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sync_utc");

                    b.Property<DateTime?>("LastSyncAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_attempt_utc");

                    b.Property<DateTime?>("LastSyncFailureUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_failure_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("NextScheduledSyncUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_scheduled_sync_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_account_id");

                    b.Property<bool>("ScheduledRefreshEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("scheduled_refresh_enabled");

                    b.Property<int>("ScheduledRefreshIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_refresh_interval_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncLeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sync_lease_expires_at_utc");

                    b.Property<Guid?>("SyncLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_lease_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NextScheduledSyncUtc")
                        .HasDatabaseName("ix_external_calendar_connections_next_sync");

                    b.HasIndex("SyncLeaseExpiresAtUtc")
                        .HasDatabaseName("ix_external_calendar_connections_lease_expires");

                    b.HasIndex("MemberId", "Provider")
                        .HasDatabaseName("ix_external_calendar_connections_member_provider");

                    b.ToTable("external_calendar_connections", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_id");

                    b.Property<string>("ICalUId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ical_uid");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("OpenInProviderUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("open_in_provider_url");

                    b.Property<string>("OriginalTimezone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_timezone");

                    b.Property<string>("ParticipantSummaryJson")
                        .HasColumnType("text")
                        .HasColumnName("participant_summary_json");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("ProviderModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_modified_at_utc");

                    b.Property<string>("RawPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_payload_hash");

                    b.Property<string>("SeriesMasterId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("series_master_id");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "StartsAtUtc")
                        .HasDatabaseName("ix_external_calendar_entries_connection_starts");

                    b.HasIndex("FeedId", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_calendar_entries_feed_event_unique");

                    b.HasIndex("FeedId", "ICalUId")
                        .HasDatabaseName("ix_external_calendar_entries_feed_ical_uid");

                    b.HasIndex("FeedId", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("ix_external_calendar_entries_feed_window");

                    b.ToTable("external_calendar_entries", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("calendar_name");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<string>("LastDeltaToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_delta_token");

                    b.Property<DateTime?>("LastSuccessfulSyncUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sync_utc");

                    b.Property<string>("ProviderCalendarId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_calendar_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc");

                    b.Property<DateTime?>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "IsSelected")
                        .HasDatabaseName("ix_external_calendar_feeds_connection_selected");

                    b.HasIndex("ConnectionId", "ProviderCalendarId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_calendar_feeds_connection_calendar_unique");

                    b.ToTable("external_calendar_feeds", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Family.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DateFormatPreference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("date_format_preference");

                    b.Property<string>("FirstDayOfWeek")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("first_day_of_week");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("primary_language_code");

                    b.HasKey("Id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Family.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<int?>("AvatarColorId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_color_id");

                    b.Property<int?>("AvatarIconId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_icon_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("HouseholdNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("household_note");

                    b.Property<bool>("IsManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manager");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preferred_name");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_email");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Responsibilities.ResponsibilityDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PrimaryOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_owner_id");

                    b.Property<string>("_secondaryOwnerIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_owner_ids");

                    b.HasKey("Id");

                    b.ToTable("responsibility_domains", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.SharedLists.SharedList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("linked_entity_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("shared_lists", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.SharedLists.SharedListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Checked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("checked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SharedListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_list_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_member_id");

                    b.HasKey("Id");

                    b.HasIndex("SharedListId");

                    b.ToTable("shared_list_items", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Tasks.HouseholdTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("household_tasks", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Tasks.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FamilyId", "Status");

                    b.ToTable("routines", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Auth.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Initialization.SystemInitializationRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("InitializedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("system_initialization", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Languages.SupportedLanguage", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("culture");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("NativeDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("native_display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_supported_languages_is_default");

                    b.ToTable("supported_languages", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Persistence.EventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Module", "OccurredAtUtc");

                    b.HasIndex("AggregateType", "AggregateId", "Version");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("DomusMind.Infrastructure.Persistence.UserFamilyAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.HasKey("UserId", "FamilyId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_family_access_user_id");

                    b.ToTable("user_family_access", (string)null);
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.CalendarEvent", b =>
                {
                    b.OwnsOne("DomusMind.Domain.Shared.HexColor", "Color", b1 =>
                        {
                            b1.Property<Guid>("CalendarEventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("color");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("calendar_events");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.OwnsOne("DomusMind.Domain.Calendar.ValueObjects.EventTime", "Time", b1 =>
                        {
                            b1.Property<Guid>("CalendarEventId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("event_date");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("event_end_date");

                            b1.Property<TimeOnly?>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("event_end_time");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("event_time_kind");

                            b1.Property<TimeOnly?>("Time")
                                .HasColumnType("time without time zone")
                                .HasColumnName("event_time");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("calendar_events");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Time")
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarConnection", b =>
                {
                    b.OwnsOne("DomusMind.Domain.Calendar.ExternalConnections.SyncHorizon", "Horizon", b1 =>
                        {
                            b1.Property<Guid>("ExternalCalendarConnectionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ForwardHorizonDays")
                                .HasColumnType("integer")
                                .HasColumnName("forward_horizon_days");

                            b1.HasKey("ExternalCalendarConnectionId");

                            b1.ToTable("external_calendar_connections");

                            b1.WithOwner()
                                .HasForeignKey("ExternalCalendarConnectionId");
                        });

                    b.Navigation("Horizon")
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarFeed", b =>
                {
                    b.HasOne("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarConnection", null)
                        .WithMany("Feeds")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Family.FamilyMember", b =>
                {
                    b.HasOne("DomusMind.Domain.Family.Family", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Responsibilities.ResponsibilityDomain", b =>
                {
                    b.OwnsOne("DomusMind.Domain.Shared.HexColor", "Color", b1 =>
                        {
                            b1.Property<Guid>("ResponsibilityDomainId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("color");

                            b1.HasKey("ResponsibilityDomainId");

                            b1.ToTable("responsibility_domains");

                            b1.WithOwner()
                                .HasForeignKey("ResponsibilityDomainId");
                        });

                    b.Navigation("Color")
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.SharedLists.SharedListItem", b =>
                {
                    b.HasOne("DomusMind.Domain.SharedLists.SharedList", null)
                        .WithMany("Items")
                        .HasForeignKey("SharedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Tasks.HouseholdTask", b =>
                {
                    b.OwnsOne("DomusMind.Domain.Shared.HexColor", "Color", b1 =>
                        {
                            b1.Property<Guid>("HouseholdTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("color");

                            b1.HasKey("HouseholdTaskId");

                            b1.ToTable("household_tasks");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdTaskId");
                        });

                    b.OwnsOne("DomusMind.Domain.Tasks.ValueObjects.TaskSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("HouseholdTaskId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date")
                                .HasColumnName("due_date");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("task_schedule_kind");

                            b1.Property<TimeOnly?>("Time")
                                .HasColumnType("time without time zone")
                                .HasColumnName("due_time");

                            b1.HasKey("HouseholdTaskId");

                            b1.ToTable("household_tasks");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdTaskId");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("DomusMind.Domain.Tasks.Routine", b =>
                {
                    b.OwnsOne("DomusMind.Domain.Shared.HexColor", "Color", b1 =>
                        {
                            b1.Property<Guid>("RoutineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("color");

                            b1.HasKey("RoutineId");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("RoutineId");
                        });

                    b.OwnsOne("DomusMind.Domain.Tasks.ValueObjects.RoutineName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoutineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("RoutineId");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("RoutineId");
                        });

                    b.OwnsOne("DomusMind.Domain.Tasks.ValueObjects.RoutineSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("RoutineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DaysOfMonth")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("schedule_days_of_month");

                            b1.Property<string>("DaysOfWeek")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("schedule_days_of_week");

                            b1.Property<TimeOnly?>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("schedule_end_time");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("schedule_frequency");

                            b1.Property<int?>("MonthOfYear")
                                .HasColumnType("integer")
                                .HasColumnName("schedule_month_of_year");

                            b1.Property<TimeOnly?>("Time")
                                .HasColumnType("time without time zone")
                                .HasColumnName("schedule_time");

                            b1.HasKey("RoutineId");

                            b1.ToTable("routines");

                            b1.WithOwner()
                                .HasForeignKey("RoutineId");
                        });

                    b.OwnsMany("DomusMind.Domain.Tasks.RoutineTargetMember", "_targetMembers", b1 =>
                        {
                            b1.Property<Guid>("routine_id")
                                .HasColumnType("uuid")
                                .HasColumnName("routine_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("member_id");

                            b1.HasKey("routine_id", "Id");

                            b1.HasIndex("Id");

                            b1.HasIndex("routine_id", "Id")
                                .IsUnique();

                            b1.ToTable("routine_target_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("routine_id");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("_targetMembers");
                });

            modelBuilder.Entity("DomusMind.Domain.Calendar.ExternalConnections.ExternalCalendarConnection", b =>
                {
                    b.Navigation("Feeds");
                });

            modelBuilder.Entity("DomusMind.Domain.Family.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DomusMind.Domain.SharedLists.SharedList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
