name: webapp-ci

on:
  pull_request:
    paths:
      - 'src/web/app/**'
  push:
    branches: [ main ]
    paths:
      - 'src/web/app/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/web/app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/web/app/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: domusmind-webapp
          path: src/web/app/dist